In [33]:
import pandas as pd
import numpy as np
from IPython.display import display
from sklearn import preprocessing
from matplotlib import pyplot as plt
import statistics

In [34]:
pd.options.display.max_columns = None

# fetch the training file
file_path_full_training_set = 'train.txt'

df = pd.read_csv(file_path_full_training_set, header=None)
df = df[(df[41] == 'land') | (df[41] == 'normal')]

In [35]:
# Dataframe befor coding

df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42
0,0,tcp,ftp_data,SF,491,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,0.0,0.0,0.0,0.0,1.00,0.00,0.00,150,25,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,normal,20
1,0,udp,other,SF,146,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,13,1,0.0,0.0,0.0,0.0,0.08,0.15,0.00,255,1,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,normal,15
3,0,tcp,http,SF,232,8153,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,5,5,0.2,0.2,0.0,0.0,1.00,0.00,0.00,30,255,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,normal,21
4,0,tcp,http,SF,199,420,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,30,32,0.0,0.0,0.0,0.0,1.00,0.00,0.09,255,255,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal,21
12,0,tcp,http,SF,287,2251,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,3,7,0.0,0.0,0.0,0.0,1.00,0.00,0.43,8,219,1.00,0.00,0.12,0.03,0.00,0.00,0.00,0.00,normal,21

In [36]:
# add the column labels
columns = (['duration'
,'protocol_type'
,'service'
,'flag'
,'src_bytes'
,'dst_bytes'
,'land'
,'wrong_fragment'
,'urgent'
,'hot'
,'num_failed_logins'
,'logged_in'
,'num_compromised'
,'root_shell'
,'su_attempted'
,'num_root'
,'num_file_creations'
,'num_shells'
,'num_access_files'
,'num_outbound_cmds'
,'is_host_login'
,'is_guest_login'
,'count'
,'srv_count'
,'serror_rate'
,'srv_serror_rate'
,'rerror_rate'
,'srv_rerror_rate'
,'same_srv_rate'
,'diff_srv_rate'
,'srv_diff_host_rate'
,'dst_host_count'
,'dst_host_srv_count'
,'dst_host_same_srv_rate'
,'dst_host_diff_srv_rate'
,'dst_host_same_src_port_rate'
,'dst_host_srv_diff_host_rate'
,'dst_host_serror_rate'
,'dst_host_srv_serror_rate'
,'dst_host_rerror_rate'
,'dst_host_srv_rerror_rate'
,'attack'
,'level'])

df.columns = columns

df.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,num_compromised,root_shell,su_attempted,num_root,num_file_creations,num_shells,num_access_files,num_outbound_cmds,is_host_login,is_guest_login,count,srv_count,serror_rate,srv_serror_rate,rerror_rate,srv_rerror_rate,same_srv_rate,diff_srv_rate,srv_diff_host_rate,dst_host_count,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,attack,level
0,0,tcp,ftp_data,SF,491,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,0.0,0.0,0.0,0.0,1.00,0.00,0.00,150,25,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,normal,20
1,0,udp,other,SF,146,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,13,1,0.0,0.0,0.0,0.0,0.08,0.15,0.00,255,1,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,normal,15
3,0,tcp,http,SF,232,8153,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,5,5,0.2,0.2,0.0,0.0,1.00,0.00,0.00,30,255,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,normal,21
4,0,tcp,http,SF,199,420,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,30,32,0.0,0.0,0.0,0.0,1.00,0.00,0.09,255,255,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal,21
12,0,tcp,http,SF,287,2251,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,3,7,0.0,0.0,0.0,0.0,1.00,0.00,0.43,8,219,1.00,0.00,0.12,0.03,0.00,0.00,0.00,0.00,normal,21

In [37]:
# Separate input and output data

input_data = df.drop(columns=['attack'])
output_data = df['attack']

In [38]:
input_data.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,num_compromised,root_shell,su_attempted,num_root,num_file_creations,num_shells,num_access_files,num_outbound_cmds,is_host_login,is_guest_login,count,srv_count,serror_rate,srv_serror_rate,rerror_rate,srv_rerror_rate,same_srv_rate,diff_srv_rate,srv_diff_host_rate,dst_host_count,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,level
0,0,tcp,ftp_data,SF,491,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,0.0,0.0,0.0,0.0,1.00,0.00,0.00,150,25,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,20
1,0,udp,other,SF,146,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,13,1,0.0,0.0,0.0,0.0,0.08,0.15,0.00,255,1,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,15
3,0,tcp,http,SF,232,8153,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,5,5,0.2,0.2,0.0,0.0,1.00,0.00,0.00,30,255,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,21
4,0,tcp,http,SF,199,420,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,30,32,0.0,0.0,0.0,0.0,1.00,0.00,0.09,255,255,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,21
12,0,tcp,http,SF,287,2251,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,3,7,0.0,0.0,0.0,0.0,1.00,0.00,0.43,8,219,1.00,0.00,0.12,0.03,0.00,0.00,0.00,0.00,21

In [39]:
output_data.head()

0     normal
1     normal
3     normal
4     normal
12    normal
Name: attack, dtype: object

In [40]:
# Encode data in dataframe

cleanup_nums = {}

for col in ('protocol_type', 'service', 'flag'):
    values = input_data[col].unique()
    cleanup_nums[col] = {}
    for num, name in enumerate(values, start=0):
        cleanup_nums[col][name] = num
        
input_data.replace(cleanup_nums, inplace=True)
input_data.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,num_compromised,root_shell,su_attempted,num_root,num_file_creations,num_shells,num_access_files,num_outbound_cmds,is_host_login,is_guest_login,count,srv_count,serror_rate,srv_serror_rate,rerror_rate,srv_rerror_rate,same_srv_rate,diff_srv_rate,srv_diff_host_rate,dst_host_count,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,level
0,0,0,0,0,491,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,2,0.0,0.0,0.0,0.0,1.00,0.00,0.00,150,25,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,20
1,0,1,1,0,146,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,13,1,0.0,0.0,0.0,0.0,0.08,0.15,0.00,255,1,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,15
3,0,0,2,0,232,8153,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,5,5,0.2,0.2,0.0,0.0,1.00,0.00,0.00,30,255,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,21
4,0,0,2,0,199,420,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,30,32,0.0,0.0,0.0,0.0,1.00,0.00,0.09,255,255,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,21
12,0,0,2,0,287,2251,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,3,7,0.0,0.0,0.0,0.0,1.00,0.00,0.43,8,219,1.00,0.00,0.12,0.03,0.00,0.00,0.00,0.00,21

In [41]:
cleanup_output = {'normal': 0.99, 'land':0.01}

output_data.replace(cleanup_output, inplace=True)

output_data.head()

0     0.99
1     0.99
3     0.99
4     0.99
12    0.99
Name: attack, dtype: float64

In [42]:
output_data = output_data.to_numpy()

output_data

array([0.99, 0.99, 0.99, ..., 0.99, 0.99, 0.99])

In [43]:
# Normalize dataframe

x = input_data.values #returns a numpy array
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
normalized_df = pd.DataFrame(x_scaled).to_numpy()

In [44]:
normalized_df

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        5.00000000e-02, 0.00000000e+00, 9.50000000e-01],
       [0.00000000e+00, 5.00000000e-01, 4.00000000e-02, ...,
        0.00000000e+00, 0.00000000e+00, 7.00000000e-01],
       [0.00000000e+00, 0.00000000e+00, 8.00000000e-02, ...,
        0.00000000e+00, 1.00000000e-02, 1.00000000e+00],
       ...,
       [1.97511357e-04, 5.00000000e-01, 2.00000000e-01, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 2.40000000e-01, ...,
        1.00000000e-02, 0.00000000e+00, 8.50000000e-01],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])

In [45]:
def sigmoid(x):
    return 1 / (1 + np.exp(-1 * x))

def sigmoid_der(x):
    return x * (1.0 - x)

In [46]:
def train(x, y, w1, w2, bias):
    temp = []
    second_layer = np.dot(x, w1) + bias[:3]
    y_second = [sigmoid(x_second) for x_second in second_layer]
    
    output = np.dot(y_second, w2) + bias[3]
    y_second.append(sigmoid(output))
    error = abs((y - y_second[-1]) / y)
    
    q13 = sigmoid_der(y_second[-1]) * (y -y_second[-1])
    for k in range(3):
        b = q13 * y_second[k]
        temp.append(w2[k] + b)
    bias[3] += b
    
    for item in range(3):
        q = sigmoid_der(y_second[item]) * q13 * w2[item]
        for k in range(42):
            b = q * x[k]
            w1[k, item] += b
        bias[item] += b
    
    w2 = []
    w2.extend(temp)
    
    return w1, w2, bias, y_second[-1], error, output

In [47]:
def online_train(x, y, w1, w2, bias, epoches):
    y_train = []
    delta_train = []
    epoch = 1
    outputs = []
    
    while epoch <= epoches:
        temp_1, temp_2 = [], []
        for k in range(len(x)):
            w1, w2, bias, result, error, output = train(x[k], y[k], w1, w2, bias)
            outputs.append(output)
            temp_1.append(result)
            temp_2.append(error)
        if epoch % 10 == 0 or epoch == 1:
            print(y[:5])
            print(outputs[:5])
            outputs = []
            print("Epoch: ", epoch)
            print("Error: ", statistics.mean(temp_2))
        y_train.append(temp_1)
        delta_train.append(temp_2)
        epoch += 1
        
        
    
    np.savetxt("w1.csv", w1, delimiter=",")
    np.savetxt("w2.csv", w2, delimiter=",")
    np.savetxt("bias.csv", bias, delimiter=",")
    
    return w1, w2, bias

In [48]:
def recognize(x, w1, w2, bias):
    print('Recognize: ')
    count_1 = 0
    count_2 = 0
    for i in range(len(x)):
        second_layer = np.dot(x[i], w1) + bias[:3]
        y_second = [sigmoid(x_second) for x_second in second_layer]
        output = np.dot(y_second, w2) + bias[3]
        res = sigmoid(output)
        y_second.append(res)
        
        if res > 0.5:
            count_1 += 1
        else:
            count_2 += 1
    
    print('Count normal: ', count_1)
    print('Count land attacks: ', count_2)
    
    return y_second[-1]

In [49]:
# Generate weights
np.random.seed(1)
w_1 = np.random.uniform(-3, 3, (42, 3))    
w_2 = np.random.uniform(-3, 3, (3, ))
bias = np.random.uniform(-3, 3, (4, ))

In [50]:
res = online_train(normalized_df, output_data, w_1, w_2,  bias, 100)

[0.99 0.99 0.99 0.99 0.99]
[0.45608490595206974, -1.3612108129222442, 2.5035310503312056, 2.751404010010834, 2.199278496507777]
Epoch:  1
Error:  0.02919583825107739
[0.99 0.99 0.99 0.99 0.99]
[4.25056598358265, 3.044051241870611, 4.7447808616347915, 4.873682969601857, 4.674977140791342]
Epoch:  10
Error:  0.026824675015140197
[0.99 0.99 0.99 0.99 0.99]
[4.36682807980033, 3.7428292733822714, 4.583711975489582, 4.636529446393898, 4.561472469912357]
Epoch:  20
Error:  0.02683327613593065
[0.99 0.99 0.99 0.99 0.99]
[4.337405038001107, 3.7146096658981205, 4.578710044311595, 4.635029779992799, 4.561299059056884]
Epoch:  30
Error:  0.019026604020112782
[0.99 0.99 0.99 0.99 0.99]
[4.229092347798026, 3.9886135202827067, 4.633625732047322, 5.053651440721683, 4.538537826906056]
Epoch:  40
Error:  0.008793185371261931
[0.99 0.99 0.99 0.99 0.99]
[4.439234053701186, 3.986434114935855, 4.513397241075065, 4.602189607030852, 4.500845868853726]
Epoch:  50
Error:  0.008202370494036609
[0.99 0.99 0.99 0.99 0.99]
[4.49153564222007, 4.0384964912692425, 4.527787740314553, 4.551771833263537, 4.524103168521661]
Epoch:  60
Error:  0.00811338573821248
[0.99 0.99 0.99 0.99 0.99]
[4.504408323590452, 4.085735343477816, 4.531371058031308, 4.541212409495261, 4.5295123698740305]
Epoch:  70
Error:  0.008085919874176013
[0.99 0.99 0.99 0.99 0.99]
[4.507621608157017, 4.12216312481309, 4.531128512875201, 4.5376454045336745, 4.529719090132033]
Epoch:  80
Error:  0.008072749997983849
[0.99 0.99 0.99 0.99 0.99]
[4.508589502726883, 4.150158664007968, 4.5302546646255415, 4.535954699779362, 4.5289751834484235]
Epoch:  90
Error:  0.008064655839896885
[0.99 0.99 0.99 0.99 0.99]
[4.508988172031454, 4.172323911435499, 4.529415322438757, 4.53494844880816, 4.52817986968645]
Epoch:  100
Error:  0.008058950070797835

In [51]:
print("Number normal attacks: ", len(output_data[output_data == 0.99]))
print("Number land attacks: ", len(output_data[output_data == 0.01]))

Number normal attacks:  67343
Number land attacks:  18

In [52]:
recognize(normalized_df, res[0], res[1], res[2])

Recognize:
Count normal:  67336
Count land attacks:  25

0.9893345175114614

In [53]:
res = online_train(normalized_df[:10000], output_data[:10000], w_1, w_2,  bias, 100)

[0.99 0.99 0.99 0.99 0.99]
[-1.0735574901170102, -0.7931863415439429, -0.6687545194038624, -0.3170044272492696, -0.3104980678471012]
Epoch:  1
Error:  0.012928785267645043
[0.99 0.99 0.99 0.99 0.99]
[4.514121513284753, 4.612573377873938, 4.793443021987546, 4.8538631502767835, 4.780208555878641]
Epoch:  10
Error:  0.007432143171018126
[0.99 0.99 0.99 0.99 0.99]
[4.509968080867512, 4.365997673058342, 4.602542301963927, 4.615301446854747, 4.599450578777054]
Epoch:  20
Error:  0.006893716081812662
[0.99 0.99 0.99 0.99 0.99]
[4.519140201710284, 4.331368406272237, 4.582338474698681, 4.589833606950904, 4.580358108874198]
Epoch:  30
Error:  0.006670597712957447
[0.99 0.99 0.99 0.99 0.99]
[4.524491426594642, 4.316479129649029, 4.576821145096337, 4.58261689090909, 4.575212552326002]
Epoch:  40
Error:  0.006542081282359291
[0.99 0.99 0.99 0.99 0.99]
[4.527313095583984, 4.3061673664911835, 4.573804756911433, 4.578752760955233, 4.5723855583358795]
Epoch:  50
Error:  0.006457567355347216
[0.99 0.99 0.99 0.99 0.99]
[4.529058952064111, 4.298147001945083, 4.571781905717705, 4.576204293975847, 4.570480315518466]
Epoch:  60
Error:  0.0063961696653894555
[0.99 0.99 0.99 0.99 0.99]
[4.530292943548381, 4.2916302896239955, 4.570307801750143, 4.574360438324863, 4.569088121759095]
Epoch:  70
Error:  0.006349163696126404
[0.99 0.99 0.99 0.99 0.99]
[4.531243841195577, 4.286213930736498, 4.569175469991125, 4.572946849036407, 4.568017220070883]
Epoch:  80
Error:  0.006311858280304273
[0.99 0.99 0.99 0.99 0.99]
[4.5320176959685625, 4.281653649840552, 4.568270555342777, 4.571816776111914, 4.567160810945921]
Epoch:  90
Error:  0.006281504384359267
[0.99 0.99 0.99 0.99 0.99]
[4.532670899371493, 4.277787220371697, 4.567524657052017, 4.570884175376041, 4.566454697117269]
Epoch:  100
Error:  0.006256229097268511

In [54]:
recognize(normalized_df, res[0], res[1], res[2])

Recognize:
Count normal:  67336
Count land attacks:  25

0.9897273077681455

In [55]:
# fetch the test file
file_path_full_test_set = 'test.txt'

df_test = pd.read_csv(file_path_full_test_set, header=None)
df_test = df_test[(df_test[41] == 'land') | (df_test[41] == 'normal')]

df_test.columns = columns

input_test_data = df_test.drop(columns=['attack'])
output_test_data = df_test['attack']

cleanup_test_nums = {}

for col in ('protocol_type', 'service', 'flag'):
    values = input_test_data[col].unique()
    cleanup_test_nums[col] = {}
    for num, name in enumerate(values, start=0):
        cleanup_test_nums[col][name] = num
        
input_test_data.replace(cleanup_test_nums, inplace=True)

cleanup_test_output = {'normal': 0.99, 'back':0.01}

output_test_data.replace(cleanup_test_output, inplace=True)

output_test_data = output_test_data.to_numpy()

x = input_test_data.values #returns a numpy array
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
normalized_test_df = pd.DataFrame(x_scaled).to_numpy()

input_test_data

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,num_compromised,root_shell,su_attempted,num_root,num_file_creations,num_shells,num_access_files,num_outbound_cmds,is_host_login,is_guest_login,count,srv_count,serror_rate,srv_serror_rate,rerror_rate,srv_rerror_rate,same_srv_rate,diff_srv_rate,srv_diff_host_rate,dst_host_count,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,level
2,2,0,0,0,12983,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0.0,0.0,0.0,0.0,1.0,0.0,0.00,134,86,0.61,0.04,0.61,0.02,0.00,0.0,0.00,0.00,21
5,0,0,1,0,267,14515,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,4,4,0.0,0.0,0.0,0.0,1.0,0.0,0.00,155,255,1.00,0.00,0.01,0.03,0.01,0.0,0.00,0.00,21
6,0,0,2,0,1022,387,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,3,0.0,0.0,0.0,0.0,1.0,0.0,1.00,255,28,0.11,0.72,0.00,0.00,0.00,0.0,0.72,0.04,21
8,0,0,1,0,327,467,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,33,47,0.0,0.0,0.0,0.0,1.0,0.0,0.04,151,255,1.00,0.00,0.01,0.03,0.00,0.0,0.00,0.00,21
11,0,0,2,0,616,330,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,2,0.0,0.0,0.0,0.0,1.0,0.0,1.00,255,129,0.51,0.03,0.00,0.00,0.00,0.0,0.33,0.00,18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22533,0,0,1,0,274,1623,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,1,0.0,0.0,0.0,0.0,1.0,0.0,0.00,92,255,1.00,0.00,0.01,0.04,0.00,0.0,0.00,0.00,21
22535,0,0,1,0,280,6087,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,3,3,0.0,0.0,0.0,0.0,1.0,0.0,0.00,5,255,1.00,0.00,0.20,0.04,0.00,0.0,0.00,0.00,21
22539,0,0,2,0,794,333,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,1,0.0,0.0,0.0,0.0,1.0,0.0,0.00,100,141,0.72,0.06,0.01,0.01,0.01,0.0,0.00,0.00,21
22540,0,0,1,0,317,938,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,2,11,0.0,0.0,0.0,0.0,1.0,0.0,0.18,197,255,1.00,0.00,0.01,0.01,0.01,0.0,0.00,0.00,21
22542,0,1,5,0,42,42,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,6,0.0,0.0,0.0,0.0,1.0,0.0,0.33,255,252,0.99,0.01,0.00,0.00,0.00,0.0,0.00,0.00,21

In [61]:
print("Number normal attacks: ", len(output_test_data[output_test_data == 0.99]))
print("Number land attacks: ", len(output_test_data[output_test_data == 0.01]))

Number normal attacks:  9711
Number land attacks:  0

In [57]:
recognize(normalized_test_df, res[0], res[1], res[2])

Recognize:
Count normal:  9713
Count land attacks:  5

0.9897107871401022

In [58]:
w1 = pd.read_csv('w1.csv', sep=',', header=None).to_numpy()
w2 = pd.read_csv('w2.csv', sep=',', header=None).to_numpy()
bias = pd.read_csv('bias.csv', sep=',', header=None).to_numpy()

In [62]:
recognize(normalized_test_df, w1, w2.T[0], bias.T[0])

Recognize:
Count normal:  9713
Count land attacks:  5

0.9897107871401022

In [64]:
recognize(normalized_df, w1, w2.T[0], bias.T[0])

Recognize:
Count normal:  67336
Count land attacks:  25

0.9897273077681455